# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages

addons:
  apt:
    packages:
      - libgsl0-dev # for topicmodels
      - libudunits2-dev # for ggraph

warnings_are_errors: true

before_install:
 - echo "options(repos = c(CRAN='http://cran.rstudio.com'))" >> ~/.Rprofile

apt_packages:
 - curl
 - libcurl4-openssl-dev

r_binary_packages:
 - topicmodels
 - rmpfr
 
r_packages:
 - covr

after_success:
 - Rscript -e 'covr::codecov()'